export const STORE_QUESTION = "STORE_QUESTION";
export const ADD_QUESTION = "ADD_QUESTION";
export const CLEAR_QUESTION = "CLEAN_QUESTION";
export const STORING_QUESTION_DB = "STORING_QUESTION_DB";
export const GETTING_QUESTIONS_DB = "GETTING_QUESTIONS_DB";
export const PUT_QUESTIONS_DB = "PUT_QUESTIONS_DB";
export const PUT_QUESTIONS_STORE = "PUT_QUESTIONS_STORE";
export const PUT_GROUPS_STORE = "PUT_GROUPS_STORE";
