version: "2"
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: typeform
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: ./config/api/Dockerfile
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: prod
      DATABASE_URL: postgres://postgres:password@db:5432/typeform
    ports:
      - "80:3001"
    depends_on:
      - db
