services:
  prueba-typeform:
    image: dvelezroman/prueba-typeform
    ports:
      - 3001:3001
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - localhost
    environment:
      - DATABASE_URL=postgres://postgres@localhost:5432/typeform
      - PORT=3001
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=typeform
