version: "2"
services:
  server:
    build: .
    command: npm start
    volumes:
      - .:/app/server/
      - /app/server/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:5432/typeform
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: typeform
